// footprint file for ergogen automatically generated by kicad-to-ergogen
// kicad footprint from piit79
// https://github.com/piit79/Kicad-STM32/blob/master/Footprints/YAAJ_WeAct_BlackPill_2.kicad_mod
// todo: silk - pins?
module.exports = {
  nets: {
    P5V: "P5V",
    P3V3: "P3V3",
    B10: "B10",
    B2: "B2",
    B1: "B1",
    B0: "B0",
    A7: "A7",
    A6: "A6",
    A5: "A5",
    A4: "A4",
    A3: "A3",
    A2: "A2",
    A1: "A1",
    A0: "A0",
    R: "R",
    C15: "C15",
    C14: "C14",
    C13: "C13",
    VB: "VB",
    B12: "B12",
    B13: "B13",
    B14: "B14",
    B15: "B15",
    A8: "A8",
    A9: "A9",
    A10: "A10",
    A11: "A11",
    A12: "A12",
    A15: "A15",
    B3: "B3",
    B4: "B4",
    B5: "B5",
    B6: "B6",
    B7: "B7",
    B8: "B8",
    B9: "B9",
    GND: "GND",
  },
  params: {
    class: "MCU",
  },
  body: (p) => {
    return `(module
      YAAJ_WeAct_BlackPill_2
      (layer F.Cu)
      (tedit 615F665A)
      ${p.at /* parametric position */}
      (tags "module Black Pill")
      (fp_text reference "${p.ref}" (at 7.62 -3.81 ${
      p.rot
    }) (layer F.SilkS) (effects (font (size 1 1) (thickness 0.15))) ${
      p.ref_hide
    })
      (pad 40 thru_hole circle (at 15.24 0 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.P5V.str})
      (pad 39 thru_hole circle (at 15.24 2.54 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.GND.str})
      (pad 38 thru_hole circle (at 15.24 5.08 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.P3V3.str})
      (pad 37 thru_hole circle (at 15.24 7.62 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.B10.str})
      (pad 36 thru_hole circle (at 15.24 10.16 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.B2.str})
      (pad 35 thru_hole circle (at 15.24 12.7 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.B1.str})
      (pad 34 thru_hole circle (at 15.24 15.24 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.B0.str})
      (pad 33 thru_hole circle (at 15.24 17.78 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.A7.str})
      (pad 32 thru_hole circle (at 15.24 20.32 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.A6.str})
      (pad 31 thru_hole circle (at 15.24 22.86 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.A5.str})
      (pad 30 thru_hole circle (at 15.24 25.4 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.A4.str})
      (pad 29 thru_hole circle (at 15.24 27.94 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.A3.str})
      (pad 28 thru_hole circle (at 15.24 30.48 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.A2.str})
      (pad 27 thru_hole circle (at 15.24 33.02 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.A1.str})
      (pad 26 thru_hole circle (at 15.24 35.56 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.A0.str})
      (pad 25 thru_hole circle (at 15.24 38.1 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.R.str})
      (pad 24 thru_hole circle (at 15.24 40.64 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.C15.str})
      (pad 23 thru_hole circle (at 15.24 43.18 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.C14.str})
      (pad 22 thru_hole circle (at 15.24 45.72 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.C13.str})
      (pad 21 thru_hole circle (at 15.24 48.26 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.VB.str})

      (pad 1 thru_hole rect (at 0 0 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.B12.str})
      (pad 2 thru_hole circle (at 0 2.54 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.B13.str})
      (pad 3 thru_hole circle (at 0 5.08 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.B14.str})
      (pad 4 thru_hole circle (at 0 7.62 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.B15.str})
      (pad 5 thru_hole circle (at 0 10.16 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.A8.str})
      (pad 6 thru_hole circle (at 0 12.7 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.A9.str})
      (pad 7 thru_hole circle (at 0 15.24 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.A10.str})
      (pad 8 thru_hole circle (at 0 17.78 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.A11.str})
      (pad 9 thru_hole circle (at 0 20.32 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.A12.str})
      (pad 10 thru_hole circle (at 0 22.86 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.A15.str})
      (pad 11 thru_hole circle (at 0 25.4 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.B3.str})
      (pad 12 thru_hole circle (at 0 27.94 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.B4.str})
      (pad 13 thru_hole circle (at 0 30.48 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.B5.str})
      (pad 14 thru_hole circle (at 0 33.02 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.B6.str})
      (pad 15 thru_hole circle (at 0 35.56 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.B7.str})
      (pad 16 thru_hole circle (at 0 38.1 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.B8.str})
      (pad 17 thru_hole circle (at 0 40.64 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.B9.str})
      (pad 18 thru_hole circle (at 0 43.18 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.P5V.str})
      (pad 19 thru_hole circle (at 0 45.72 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.GND.str})
      (pad 20 thru_hole circle (at 0 48.26 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.P3V3.str})
    )`;
  },
};
