// footprint file for ergogen automatically generated by kicad-to-ergogen
// kicad footprint from piit79
// https://github.com/piit79/Kicad-STM32/blob/master/Footprints/YAAJ_WeAct_BlackPill_SWD_2.kicad_mod
// modified by secretpocketcat
module.exports = {
  nets: {
    P5V: "P5V",
    P3V3: "P3V3",
    B10: "B10",
    B2: "B2",
    B1: "B1",
    B0: "B0",
    A7: "A7",
    A6: "A6",
    A5: "A5",
    A4: "A4",
    A3: "A3",
    A2: "A2",
    A1: "A1",
    A0: "A0",
    R: "R",
    C15: "C15",
    C14: "C14",
    C13: "C13",
    VB: "VB",
    B12: "B12",
    B13: "B13",
    B14: "B14",
    B15: "B15",
    A8: "A8",
    A9: "A9",
    A10: "A10",
    A11: "A11",
    A12: "A12",
    A15: "A15",
    B3: "B3",
    B4: "B4",
    B5: "B5",
    B6: "B6",
    B7: "B7",
    B8: "B8",
    B9: "B9",
    GND: "GND",
  },
  params: {
    class: "custom",
  },
  body: (p) => {
    return `(module
      YAAJ_WeAct_BlackPill_SWD_2
      (layer F.Cu)
      (tedit 615F665A)
      ${p.at /* parametric position */}
      (tags "module Black Pill header SWD breakout")
      (fp_text reference "${p.ref}" (at 7.62 -3.81 ${
      p.rot
    }) (layer F.SilkS) (effects (font (size 1 1) (thickness 0.15))) ${
      p.ref_hide
    })
      (fp_text value "WeAct BlackPill" (at 20.32 24.765 ${
        90 + p.rot
      }) (layer F.Fab) hide (effects (font (size 1 1) (thickness 0.15))))
      (fp_line (start -1.33 0) (end -1.33 -1.33) (layer F.SilkS) (width 0.12))
      (fp_line (start 16.51 49.53) (end 13.97 49.53) (layer F.SilkS) (width 0.12))
      (fp_line (start 13.97 -1.27) (end 16.51 -1.27) (layer F.SilkS) (width 0.12))
      (fp_line (start 1.33 49.59) (end -1.33 49.59) (layer F.SilkS) (width 0.12))
      (fp_line (start -1.33 1.27) (end 1.33 1.27) (layer F.SilkS) (width 0.12))
      (fp_line (start 13.44 45.72) (end 13.44 50.06) (layer F.CrtYd) (width 0.05))
      (fp_line (start 13.44 -1.8) (end 13.44 45.72) (layer F.CrtYd) (width 0.05))
      (fp_line (start 1.8 45.72) (end 1.8 50.06) (layer F.CrtYd) (width 0.05))
      (fp_line (start 1.8 -1.8) (end 1.8 45.72) (layer F.CrtYd) (width 0.05))
      (fp_line (start 17.04 50.06) (end 13.44 50.06) (layer F.CrtYd) (width 0.05))
      (fp_line (start 17.04 -1.8) (end 17.04 50.06) (layer F.CrtYd) (width 0.05))
      (fp_line (start 13.44 -1.8) (end 17.04 -1.8) (layer F.CrtYd) (width 0.05))
      (fp_line (start 1.8 -1.8) (end -1.8 -1.8) (layer F.CrtYd) (width 0.05))
      (fp_line (start -1.8 50.06) (end 1.8 50.06) (layer F.CrtYd) (width 0.05))
      (fp_line (start -1.8 -1.8) (end -1.8 50.06) (layer F.CrtYd) (width 0.05))
      (fp_line (start -3.93 50.88) (end -3.93 -2.62) (layer F.CrtYd) (width 0.05))
      (fp_line (start 19.17 50.88) (end -3.93 50.88) (layer F.CrtYd) (width 0.05))
      (fp_line (start 19.17 -2.62) (end 19.17 50.88) (layer F.CrtYd) (width 0.05))
      (fp_line (start -3.93 -2.62) (end 19.17 -2.62) (layer F.CrtYd) (width 0.05))
      (fp_line (start -3.68 -2.37) (end 18.92 -2.37) (layer F.Fab) (width 0.12))
      (fp_line (start -3.68 50.63) (end -3.68 -2.32) (layer F.Fab) (width 0.12))
      (fp_line (start -3.68 50.63) (end 18.92 50.63) (layer F.Fab) (width 0.12))
      (fp_line (start 18.92 -2.37) (end 18.92 50.63) (layer F.Fab) (width 0.12))
      (fp_line (start 18.995 50.705) (end -3.755 50.705) (layer F.SilkS) (width 0.12))
      (fp_line (start -3.755 -2.445) (end 18.995 -2.445) (layer F.SilkS) (width 0.12))
      (fp_line (start 3.72 3.48) (end 11.52 3.48) (layer F.Fab) (width 0.1))
      (fp_line (start 3.72 3.48) (end 3.72 -2.32) (layer F.Fab) (width 0.1))
      (fp_line (start 11.52 3.48) (end 11.52 -2.32) (layer F.Fab) (width 0.1))
      (fp_line (start -1.27 -0.635) (end -0.635 -1.27) (layer F.Fab) (width 0.1))
      (fp_line (start -0.635 -1.27) (end 1.27 -1.27) (layer F.Fab) (width 0.1))
      (fp_line (start 1.27 -1.27) (end 1.27 49.53) (layer F.Fab) (width 0.1))
      (fp_line (start 1.27 49.53) (end -1.27 49.53) (layer F.Fab) (width 0.1))
      (fp_line (start -1.27 49.53) (end -1.27 -0.635) (layer F.Fab) (width 0.1))
      (fp_line (start 13.97 -1.27) (end 16.51 -1.27) (layer F.Fab) (width 0.1))
      (fp_line (start 16.51 -1.27) (end 16.51 49.53) (layer F.Fab) (width 0.1))
      (fp_line (start 16.51 49.53) (end 13.97 49.53) (layer F.Fab) (width 0.1))
      (fp_line (start 13.97 49.53) (end 13.97 -1.27) (layer F.Fab) (width 0.1))
      (fp_text user REF** (at 7.62 24.13 ${
        90 + p.rot
      }) (layer F.Fab) (effects (font (size 1 1) (thickness 0.15))))
      (fp_text user Y@@J (at 2.921 -1.016 ${
        90 + p.rot
      }) (layer Dwgs.User) (effects (font (size 0.5 0.5) (thickness 0.1))))
      (fp_line (start 2.542 43.179) (end 12.702 43.179) (layer F.Fab) (width 0.1))
      (fp_line (start 12.702 43.179) (end 12.702 45.719) (layer F.Fab) (width 0.1))
      (fp_line (start 12.702 45.719) (end 2.542 45.719) (layer F.Fab) (width 0.1))
      (fp_line (start 2.542 45.719) (end 2.542 43.179) (layer F.Fab) (width 0.1))
      (fp_line (start 2.482 45.779) (end 12.762 45.779) (layer F.SilkS) (width 0.12))
      (fp_line (start 2.482 43.119) (end 2.482 45.779) (layer F.SilkS) (width 0.12))
      (fp_line (start 2.012 46.249) (end 2.012 42.649) (layer F.CrtYd) (width 0.05))
      (fp_line (start 13.232 46.249) (end 2.012 46.249) (layer F.CrtYd) (width 0.05))
      (fp_line (start 13.232 42.649) (end 13.232 46.249) (layer F.CrtYd) (width 0.05))
      (fp_line (start 13.232 42.649) (end 2.012 42.649) (layer F.CrtYd) (width 0.05))
      
      (pad 40 thru_hole circle (at 15.24 0 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.P5V.str})
      (pad 39 thru_hole circle (at 15.24 2.54 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.GND.str})
      (pad 38 thru_hole circle (at 15.24 5.08 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.P3V3.str})
      (pad 37 thru_hole circle (at 15.24 7.62 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.B10.str})
      (pad 36 thru_hole circle (at 15.24 10.16 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.B2.str})
      (pad 35 thru_hole circle (at 15.24 12.7 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.B1.str})
      (pad 34 thru_hole circle (at 15.24 15.24 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.B0.str})
      (pad 33 thru_hole circle (at 15.24 17.78 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.A7.str})
      (pad 32 thru_hole circle (at 15.24 20.32 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.A6.str})
      (pad 31 thru_hole circle (at 15.24 22.86 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.A5.str})
      (pad 30 thru_hole circle (at 15.24 25.4 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.A4.str})
      (pad 29 thru_hole circle (at 15.24 27.94 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.A3.str})
      (pad 28 thru_hole circle (at 15.24 30.48 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.A2.str})
      (pad 27 thru_hole circle (at 15.24 33.02 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.A1.str})
      (pad 26 thru_hole circle (at 15.24 35.56 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.A0.str})
      (pad 25 thru_hole circle (at 15.24 38.1 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.R.str})
      (pad 24 thru_hole circle (at 15.24 40.64 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.C15.str})
      (pad 23 thru_hole circle (at 15.24 43.18 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.C14.str})
      (pad 22 thru_hole circle (at 15.24 45.72 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.C13.str})
      (pad 21 thru_hole circle (at 15.24 48.26 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.VB.str})

      (pad 1 thru_hole rect (at 0 0 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.B12.str})
      (pad 2 thru_hole circle (at 0 2.54 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.B13.str})
      (pad 3 thru_hole circle (at 0 5.08 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.B14.str})
      (pad 4 thru_hole circle (at 0 7.62 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.B15.str})
      (pad 5 thru_hole circle (at 0 10.16 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.A8.str})
      (pad 6 thru_hole circle (at 0 12.7 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.A9.str})
      (pad 7 thru_hole circle (at 0 15.24 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.A10.str})
      (pad 8 thru_hole circle (at 0 17.78 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.A11.str})
      (pad 9 thru_hole circle (at 0 20.32 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.A12.str})
      (pad 10 thru_hole circle (at 0 22.86 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.A15.str})
      (pad 11 thru_hole circle (at 0 25.4 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.B3.str})
      (pad 12 thru_hole circle (at 0 27.94 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.B4.str})
      (pad 13 thru_hole circle (at 0 30.48 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.B5.str})
      (pad 14 thru_hole circle (at 0 33.02 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.B6.str})
      (pad 15 thru_hole circle (at 0 35.56 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.B7.str})
      (pad 16 thru_hole circle (at 0 38.1 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.B8.str})
      (pad 17 thru_hole circle (at 0 40.64 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.B9.str})
      (pad 18 thru_hole circle (at 0 43.18 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.P5V.str})
      (pad 19 thru_hole circle (at 0 45.72 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.GND.str})
      (pad 20 thru_hole circle (at 0 48.26 ${
        p.rot
      }) (size 1.7 1.7) (drill 1) (layers *.Cu *.Mask) ${p.net.P3V3.str})
    )`;
  },
};
